apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: faas
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkZXZraXRucmVnaXN0cnkuYXp1cmVjci5pbyI6IHsKCQkJImF1dGgiOiAiWkdWMmEybDBibkpsWjJsemRISjVPamg2VTNKTVMxWjFjR3RJTmpkSlpUUnZZMk5WTDNwTVowVTNha2x1Y2xvNGRGaEpVVWszTVZGdVZTdEJRMUpDZEV4TFpFbz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: faas
  annotations:
    networking.knative.dev/http-protocol: "redirected"
    features.knative.dev/http-full-duplex: "Enabled" # Test with your http clients before enabling, as older clients may not provide support for HTTP/1 full duplex.
spec:
  template:
    spec:
      containers:
        - image: devkitnregistry.azurecr.io/func:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: faas-hello
  namespace: istio-system
spec:
  secretName: faas-hello
  commonName: 'test.knative.k8sdemocluster.com'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "faas"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "faas"
  dnsNames:
    - 'test.knative.k8sdemocluster.com'
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: 'test.knative.k8sdemocluster.com'
spec:
  namespace: faas
---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: 'test.knative.k8sdemocluster.com'
  namespace: faas
spec:
  ref:
    name: hello
    kind: Service
    apiVersion: serving.knative.dev/v1
  tls:
    secretName: faas-hello
