kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kitn-user-full-access
  namespace: kitn
rules:
  - apiGroups: [ "", "extensions", "apps" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "batch" ]
    resources:
      - jobs
      - cronjobs
    verbs: [ "*" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-access
  namespace: kitn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kitn-user-full-access
subjects:
  - kind: Group
    namespace: kitn
    name: groupObjectId